Note: you may need to restart the kernel to use updated packages.

In [13]:
import pandas as pd
from mlxtend.preprocessing import TransactionEncoder
from mlxtend.frequent_patterns import apriori
from mlxtend.frequent_patterns import association_rules 
from IPython.display import display_html

In [15]:
def dataset():
   data = [['Milk', 'Onion', 'Nutmeg', 'Kidney Beans', 'Eggs', 'Yogurt'],
           ['Dill', 'Onion', 'Nutmeg', 'Kidney Beans', 'Eggs', 'Yogurt'],
           ['Milk', 'Apple', 'Kidney Beans', 'Eggs'],
           ['Milk', 'Unicorn', 'Corn', 'Kidney Beans', 'Yogurt'],
           ['Corn', 'Onion', 'Onion', 'Kidney Beans', 'Ice cream', 'Eggs']]
#     data = [['Milk','Onion','Nutmeg', 'Kidney Beans','Eggs', 'Yogurt'],
#             ['Dill','Onion','Nutmeg','Kidney Beans','Eggs','Yogurt'],
#            ['Milk','Apple','Kidney Beans','Eggs'],
#            ['Milk','Unicorn','Corn','Eggs'],
#            ['Corn','Onion','Onion','Kidney Beans','Ice Cream','Eggs']]
   # data=[['I1','I2','I3'],['I2','I3','I4'],['I4','I5'],['I1','I2','I4'],['I1','I2','I3','I5'],['I1','I2','I3','I4']]
    print("The given raw data:")
    print(data)
    te = TransactionEncoder()
    te_ary = te.fit(data).transform(data)
    df = pd.DataFrame(te_ary, columns = te.columns_)
    print("The encoded data:")
    print("Encoded data:")
    display_html(df)
    return df

In [17]:
def association_rule(frequent_itemsets):
    print("Enter your metric of interest confidence or lift:")
    choice = input()
    if choice == 'confidence':
        print("Enter minimum confidence threshold value:")
        min_confidence = float(input())
        rule = association_rules(frequent_itemsets, metric = "confidence", min_threshold = min_confidence)
    elif choice == 'lift':
        print("Enter the minimum lift threshold value:")
        min_lift = float(input())
        rule = association_rules(frequent_itemsets, metric = "lift", min_threshold = min_lift)
    print("Do you want to view the learned association rules?")
    choice = input()
    if choice == 'yes':
        display_html(rule.drop(['leverage','conviction'], axis = 1))
    else:
        quit()

In [18]:
def main():
    data = dataset()
    frequent_itemsets = frequent_itemset(data)
    association_rule(frequent_itemsets)
main()

The given raw data:
[['Milk', 'Onion', 'Nutmeg', 'Kidney Beans', 'Eggs', 'Yogurt'], ['Dill', 'Onion', 'Nutmeg', 'Kidney Beans', 'Eggs', 'Yogurt'], ['Milk', 'Apple', 'Kidney Beans', 'Eggs'], ['Milk', 'Unicorn', 'Corn', 'Kidney Beans', 'Yogurt'], ['Corn', 'Onion', 'Onion', 'Kidney Beans', 'Ice cream', 'Eggs']]
The encoded data:
Encoded data:

,Apple,Corn,Dill,Eggs,Ice cream,Kidney Beans,Milk,Nutmeg,Onion,Unicorn,Yogurt
0,False,False,False,True,False,True,True,True,True,False,True
1,False,False,True,True,False,True,False,True,True,False,True
2,True,False,False,True,False,True,True,False,False,False,False
3,False,True,False,False,False,True,True,False,False,True,True
4,False,True,False,True,True,True,False,False,True,False,False

The value of minimum support threshold used is 0.6
Do you want to value frequent itemsets generated by Apriori?
yes
Frequent itemsets:

,support,itemsets
0,0.8,(Eggs)
1,1.0,(Kidney Beans)
2,0.6,(Milk)
3,0.6,(Onion)
4,0.6,(Yogurt)
5,0.8,"(Eggs, Kidney Beans)"
6,0.6,"(Onion, Eggs)"
7,0.6,"(Milk, Kidney Beans)"
8,0.6,"(Onion, Kidney Beans)"
9,0.6,"(Yogurt, Kidney Beans)"
10,0.6,"(Onion, Eggs, Kidney Beans)"

Enter your metric of interest confidence or lift:
confidence
Enter minimum confidence threshold value:
0.8
Do you want to view the learned association rules?
yes

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift
0,(Eggs),(Kidney Beans),0.8,1.0,0.8,1.0,1.00
1,(Kidney Beans),(Eggs),1.0,0.8,0.8,0.8,1.00
2,(Onion),(Eggs),0.6,0.8,0.6,1.0,1.25
3,(Milk),(Kidney Beans),0.6,1.0,0.6,1.0,1.00
4,(Onion),(Kidney Beans),0.6,1.0,0.6,1.0,1.00
5,(Yogurt),(Kidney Beans),0.6,1.0,0.6,1.0,1.00
6,"(Onion, Eggs)",(Kidney Beans),0.6,1.0,0.6,1.0,1.00
7,"(Onion, Kidney Beans)",(Eggs),0.6,0.8,0.6,1.0,1.25
8,(Onion),"(Eggs, Kidney Beans)",0.6,0.8,0.6,1.0,1.25